# fly.toml app configuration file generated for patientportal-dev on 2025-01-14T20:53:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'patientportal-dev'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
